### ISSUE TITLE
Reference to wrong chapter numbers in chapter 1.5

### ISSUE THREAD

**Issue by Martinsbl** [NordicSemiconductor/nrf52-production-programming#1]
In chapter 1.5, "Verify (Optional)", there are references to  chapter 4.7 and 4.8: 
_"Make sure not to reset between steps 4.7 Write data and 4.8 Verify."_
These chapters are not present in the paper.

**Comment by mjdietzx** [comment]
Fixed: 5d577d83f144cca148b11a6fa3d9534566abe5b3.
